### ISSUE TITLE
Migrate away from inline css and styled components

### ISSUE THREAD

**Issue by CharlieS1103** [laroccol/typeo#12]
Should probably use multiple scss files in a styles folder and compile it into a singular styles.css file with an npm script for organization purposes. Plus will reduce code clutter

**Comment by laroccol** [comment]
While I agree some of the inline styles should be cleaned up, I think I would like to keep using the sx prop to apply styles to the components. I like to keep the styles coupled with the component, and using mui it makes it easier to hook into the theme. This will also make it easier to make custom themes because you just have to edit the createTheme object.

The thing I think needs to be cleaned up is defining the styles directly in the sx props. Instead you can create an object for the styles and pass that in to the props. For example:

Instead of :

<Box sx={{width: 100, height: 100}}/></Box>

It would be:

const styles = { myBox: {width: 100, height: 100}}

<Box sx={styles.myBox} /></Box>
